-- Auditoria inalterable para los usuarios de la aplicacion.
-- Registra cambios posteriores a la instalacion de este archivo.

begin;

create table if not exists public.auditoria_eventos (
  id bigint generated by default as identity primary key,
  ocurrido_en timestamp with time zone not null default clock_timestamp(),
  transaccion_id bigint not null default txid_current(),
  usuario_id uuid,
  usuario_nombre text not null default '',
  usuario_rol text not null default '',
  accion text not null,
  esquema text not null,
  tabla text not null,
  registro_id text not null default '',
  datos_antes jsonb,
  datos_despues jsonb,
  cambios jsonb not null default '{}'::jsonb,
  origen text not null default '',
  constraint auditoria_eventos_accion_valida
    check (accion in ('INSERT', 'UPDATE', 'DELETE'))
);

create index if not exists idx_auditoria_eventos_ocurrido_en
on public.auditoria_eventos (ocurrido_en desc);

create index if not exists idx_auditoria_eventos_tabla_registro
on public.auditoria_eventos (tabla, registro_id, ocurrido_en desc);

create index if not exists idx_auditoria_eventos_usuario
on public.auditoria_eventos (usuario_id, ocurrido_en desc);

create index if not exists idx_auditoria_eventos_transaccion
on public.auditoria_eventos (transaccion_id);

create or replace function public.auditoria_calcular_cambios(
  p_antes jsonb,
  p_despues jsonb
)
returns jsonb
language sql
immutable
set search_path = ''
as $$
  select coalesce(
    jsonb_object_agg(
      claves.clave,
      jsonb_build_object(
        'antes', coalesce(p_antes, '{}'::jsonb) -> claves.clave,
        'despues', coalesce(p_despues, '{}'::jsonb) -> claves.clave
      )
      order by claves.clave
    ),
    '{}'::jsonb
  )
  from (
    select clave
    from jsonb_object_keys(coalesce(p_antes, '{}'::jsonb)) as anterior(clave)
    union
    select clave
    from jsonb_object_keys(coalesce(p_despues, '{}'::jsonb)) as posterior(clave)
  ) claves
  where coalesce(p_antes, '{}'::jsonb) -> claves.clave
    is distinct from coalesce(p_despues, '{}'::jsonb) -> claves.clave;
$$;

create or replace function public.registrar_evento_auditoria()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_antes jsonb;
  v_despues jsonb;
  v_usuario_id uuid := auth.uid();
  v_usuario_nombre text := '';
  v_usuario_rol text := '';
  v_registro_id text := '';
  v_origen text := '';
begin
  if tg_op = 'INSERT' then
    v_despues := to_jsonb(new);
  elsif tg_op = 'UPDATE' then
    v_antes := to_jsonb(old);
    v_despues := to_jsonb(new);

    if v_antes = v_despues then
      return new;
    end if;
  elsif tg_op = 'DELETE' then
    v_antes := to_jsonb(old);
  else
    raise exception 'Operacion de auditoria no soportada: %', tg_op;
  end if;

  if v_usuario_id is not null then
    -- Si un admin modifica su propio perfil, se conserva el rol previo como
    -- identidad del actor de esa operacion.
    if tg_table_name = 'perfiles'
      and tg_op in ('UPDATE', 'DELETE')
      and v_antes->>'id' = v_usuario_id::text then
      v_usuario_nombre := coalesce(v_antes->>'nombre', '');
      v_usuario_rol := coalesce(v_antes->>'rol', '');
    else
      select
        coalesce(perfil.nombre, ''),
        coalesce(perfil.rol, '')
      into v_usuario_nombre, v_usuario_rol
      from public.perfiles perfil
      where perfil.id = v_usuario_id;
    end if;
  end if;

  v_registro_id := coalesce(
    v_despues->>'id',
    v_antes->>'id',
    v_despues->>'codigo_bodega',
    v_antes->>'codigo_bodega',
    ''
  );

  v_origen := coalesce(nullif(current_setting('request.path', true), ''), 'base_datos');

  insert into public.auditoria_eventos (
    ocurrido_en,
    transaccion_id,
    usuario_id,
    usuario_nombre,
    usuario_rol,
    accion,
    esquema,
    tabla,
    registro_id,
    datos_antes,
    datos_despues,
    cambios,
    origen
  ) values (
    clock_timestamp(),
    txid_current(),
    v_usuario_id,
    v_usuario_nombre,
    v_usuario_rol,
    tg_op,
    tg_table_schema,
    tg_table_name,
    v_registro_id,
    v_antes,
    v_despues,
    public.auditoria_calcular_cambios(v_antes, v_despues),
    v_origen
  );

  -- Es un trigger AFTER; el valor retornado no modifica la operacion original.
  return null;
end;
$$;

revoke all on function public.auditoria_calcular_cambios(jsonb, jsonb) from public;
revoke all on function public.auditoria_calcular_cambios(jsonb, jsonb) from anon;
revoke all on function public.auditoria_calcular_cambios(jsonb, jsonb) from authenticated;

revoke all on function public.registrar_evento_auditoria() from public;
revoke all on function public.registrar_evento_auditoria() from anon;
revoke all on function public.registrar_evento_auditoria() from authenticated;

do $$
declare
  v_tabla text;
begin
  foreach v_tabla in array array[
    'perfiles',
    'vales_bodega',
    'vales_bodega_items',
    'bodega_inventarios',
    'bodega_inventario_items',
    'bodega_recepciones',
    'bodega_recepcion_items',
    'bodega_despachos',
    'bodega_despacho_items'
  ]
  loop
    if to_regclass(format('public.%I', v_tabla)) is not null then
      execute format(
        'drop trigger if exists trigger_auditoria_cambios on public.%I',
        v_tabla
      );
      execute format(
        'create trigger trigger_auditoria_cambios
         after insert or update or delete on public.%I
         for each row execute function public.registrar_evento_auditoria()',
        v_tabla
      );
    end if;
  end loop;
end;
$$;

alter table public.auditoria_eventos enable row level security;
alter table public.auditoria_eventos force row level security;

drop policy if exists auditoria_eventos_select_admin on public.auditoria_eventos;
create policy auditoria_eventos_select_admin
on public.auditoria_eventos
for select
to authenticated
using (public.usuario_tiene_rol(array['admin']));

revoke all on table public.auditoria_eventos from public;
revoke all on table public.auditoria_eventos from anon;
revoke all on table public.auditoria_eventos from authenticated;
grant select on table public.auditoria_eventos to authenticated;

do $$
begin
  if to_regclass('public.auditoria_eventos_id_seq') is not null then
    revoke all on sequence public.auditoria_eventos_id_seq from public;
    revoke all on sequence public.auditoria_eventos_id_seq from anon;
    revoke all on sequence public.auditoria_eventos_id_seq from authenticated;
  end if;
end;
$$;

commit;

select
  event_object_table as tabla,
  trigger_name,
  string_agg(event_manipulation, ', ' order by event_manipulation) as eventos
from information_schema.triggers
where trigger_schema = 'public'
  and trigger_name = 'trigger_auditoria_cambios'
group by event_object_table, trigger_name
order by event_object_table;
